PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX eli: <http://data.europa.eu/eli/ontology#>
INSERT {
  GRAPH <$syncGraph> {
    ?s ?p ?o.
    ?s <http://www.semanticdesktop.org/ontologies/2007/08/15/nao#score> "10"^^xsd:float.
    ?s mu:uuid ?uuid.
  }
}
WHERE {
  GRAPH <$tmpGraph> {
     ?s a besluit:Besluit;
        ?p ?o.
     BIND(REPLACE(STR(?s), 'http://data.lblod.info/id/besluiten/','') as ?uuid)
  }
}