PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX eli: <http://data.europa.eu/eli/ontology#>
INSERT {
  GRAPH <$syncGraph> {
    ?s ?p ?o.
    ?s mu:uuid ?uuid.
  }
}
WHERE {
  GRAPH <$tmpGraph> {
     ?artikel a besluit:Artikel;
        ext:bekrachtigtAanstellingVan ?s.
     ?s ?p ?o.
     BIND(REPLACE(STR(?s), 'http://data.lblod.info/id/mandatarissen/','') as ?uuid)
  }
}
